# Generated by Django 4.1.3 on 2023-02-17 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[(None, 'סוג התיק'), ('תאונת דרכים', 'תאונת דרכים'), ('מלל בלבד', 'מלל בלבד'), ('חבויות', 'חבויות'), ('פוליסה', 'פוליסה'), ('רשלנות רפואית', 'רשלנות רפואית'), ('תלמידים', 'תלמידים'), ('תעבורה', 'תעבורה'), ('פלילי', 'פלילי'), ('פלילי', 'פנסיה'), ('הגנה', 'הגנה'), ('אחר', 'אחר')], default='אחר', max_length=50, verbose_name='סוג תיק')),
                ('status', models.CharField(choices=[(None, 'מצב התיק'), ('פעיל', 'פעיל'), ('לא פעיל', 'לא פעיל'), ('סגור', 'סגור')], default='פעיל', max_length=10, verbose_name='מצב התיק')),
                ('open_date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך פתיחה')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='תאריך סגירה')),
                ('superior', models.CharField(choices=[(None, 'מטפל'), ('נאורי', 'נאורי'), ('ארז', 'ארז'), ('מיכאל', 'מיכאל'), ('מזכירות1', 'מזכירות1'), ('מזכירות2', 'מזכירות2'), ('מתמחה', 'מתמחה')], default='נאורי', max_length=10, verbose_name='מטפל')),
                ('work_accident', models.BooleanField(verbose_name='תאונת עבודה')),
            ],
            options={
                'verbose_name': 'סוג תיק',
                'verbose_name_plural': 'סוגי תיקים',
            },
        ),
        migrations.CreateModel(
            name='MyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, verbose_name='תעודת זהות')),
                ('first_name', models.CharField(max_length=20, verbose_name='שם משפחה')),
                ('last_name', models.CharField(max_length=20, verbose_name='שם פרטי')),
                ('birth_date', models.DateField(default='1993-07-24', verbose_name='תאריך לידה')),
                ('gender', models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה'), ('אחר', 'אחר')], default='זכר', max_length=10, verbose_name='מין')),
                ('phone1_prefix', models.CharField(choices=[(None, 'קידומת'), ('050', '050'), ('051', '051'), ('052', '052'), ('053', '053'), ('054', '054'), ('055', '055'), ('056', '056'), ('058', '058'), ('059', '059'), ('02', '02'), ('03', '03'), ('04', '04'), ('08', '08'), ('09', '09')], default='050', max_length=3, verbose_name='')),
                ('phone1', models.CharField(max_length=7, verbose_name='טלפון 1')),
                ('phone2_prefix', models.CharField(blank=True, choices=[(None, 'קידומת'), ('050', '050'), ('051', '051'), ('052', '052'), ('053', '053'), ('054', '054'), ('055', '055'), ('056', '056'), ('058', '058'), ('059', '059'), ('02', '02'), ('03', '03'), ('04', '04'), ('08', '08'), ('09', '09')], default='', max_length=3, verbose_name='')),
                ('phone2', models.CharField(blank=True, default='', max_length=7, verbose_name='טלפון 2')),
                ('address_city', models.CharField(default='', max_length=20, verbose_name='ישוב')),
                ('address_street', models.CharField(default='', max_length=20, verbose_name='רחוב')),
                ('address_number', models.CharField(default='', max_length=3, verbose_name='מספר')),
                ('address_pob', models.CharField(blank=True, default='', max_length=7, verbose_name='תא דואר')),
                ('address_zip', models.CharField(blank=True, default='', max_length=7, verbose_name='מיקוד')),
                ('mail', models.EmailField(blank=True, default='', max_length=254, verbose_name='דואר אלקטרוני')),
                ('kupa', models.CharField(choices=[('כללית', 'כללית'), ('מכבי', 'מכבי'), ('מאוחדת', 'מאוחדת'), ('לאומית', 'לאומית'), ('צה"ל', 'צה"ל')], default='כללית', max_length=10, verbose_name='קופת חולים')),
                ('occupation', models.CharField(blank=True, default='', max_length=20, verbose_name='עיסוק')),
            ],
            options={
                'verbose_name': 'לקוח',
                'verbose_name_plural': 'לקוחות',
            },
        ),
        migrations.CreateModel(
            name='PhonePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_prefix', models.CharField(max_length=10, verbose_name='ccccccc')),
            ],
            options={
                'verbose_name': 'קידומת',
                'verbose_name_plural': 'קידומות',
            },
        ),
        migrations.CreateModel(
            name='TadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='תאריך תאונה')),
                ('event_place', models.CharField(max_length=50, verbose_name='מקום התאונה')),
                ('car_number', models.CharField(max_length=11, verbose_name='מספר רכב')),
                ('insurance_company', models.CharField(max_length=50, verbose_name='מבטחת')),
                ('evacuation', models.BooleanField(verbose_name='אמבולנס')),
                ('involvment', models.CharField(choices=[(None, 'מעורבות'), ('נהג', 'נהג'), ('נוסע', 'נוסע'), ('הולך רגל', 'הולך רגל')], default='מעורבות', max_length=10, verbose_name='מעורבות')),
                ('circumstances', models.TextField(verbose_name='נסיבות')),
                ('first_aid', models.TextField(verbose_name='טיפול ראשוני')),
                ('complaints_and_findings', models.TextField(verbose_name='וממצאים תלונות')),
                ('follow_up', models.TextField(verbose_name='המשך טיפול')),
                ('sick_leave', models.CharField(max_length=20, verbose_name='חופשת מחלה')),
                ('damage', models.CharField(max_length=20, verbose_name='אסמכתא לנזק')),
                ('missing_documents', models.TextField(verbose_name='מסמכים חסרים')),
                ('file_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snslaw.clientfiles')),
            ],
            options={
                'verbose_name': 'תיק תד',
                'verbose_name_plural': 'תיקי תד',
            },
        ),
        migrations.AddField(
            model_name='clientfiles',
            name='file_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snslaw.myclient'),
        ),
    ]
