# Generated by Django 4.1.3 on 2023-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snslaw', '0003_author_publisher_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclient',
            name='id_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='תעודת זהות'),
        ),
        migrations.AlterField(
            model_name='tadfile',
            name='complaints_and_findings',
            field=models.TextField(verbose_name=' תלונות וממצאים'),
        ),
    ]
