# Generated by Django 4.1.3 on 2023-02-23 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snslaw', '0004_alter_myclient_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_accident', models.BooleanField(verbose_name='תאונת עבודה')),
                ('status', models.CharField(choices=[(None, 'מצב התיק'), ('פעיל', 'פעיל'), ('לא פעיל', 'לא פעיל'), ('סגור', 'סגור')], default='פעיל', max_length=10, verbose_name='מצב התיק')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='תאריך סגירה')),
                ('open_date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך פתיחה')),
                ('event_date', models.DateField(verbose_name='תאריך תאונה')),
                ('event_place', models.CharField(max_length=50, verbose_name='מקום התאונה')),
                ('car_number', models.CharField(max_length=11, verbose_name='מספר רכב')),
                ('insurance_company', models.CharField(max_length=50, verbose_name='מבטחת')),
                ('evacuation', models.BooleanField(verbose_name='אמבולנס')),
                ('involvment', models.CharField(choices=[(None, 'מעורבות'), ('נהג', 'נהג'), ('נוסע', 'נוסע'), ('הולך רגל', 'הולך רגל')], default='מעורבות', max_length=10, verbose_name='מעורבות')),
                ('circumstances', models.TextField(verbose_name='נסיבות')),
                ('first_aid', models.TextField(verbose_name='טיפול ראשוני')),
                ('complaints_and_findings', models.TextField(verbose_name=' תלונות וממצאים')),
                ('follow_up', models.TextField(verbose_name='המשך טיפול')),
                ('sick_leave', models.CharField(max_length=20, verbose_name='חופשת מחלה')),
                ('damage', models.CharField(max_length=20, verbose_name='אסמכתא לנזק')),
                ('missing_documents', models.TextField(verbose_name='מסמכים חסרים')),
                ('file_header', models.ForeignKey(default='תאונת דרכים', on_delete=django.db.models.deletion.CASCADE, to='snslaw.clientfiles')),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snslaw.myclient')),
            ],
            options={
                'verbose_name': 'תיק תד',
                'verbose_name_plural': 'תיקי תד',
            },
        ),
        migrations.DeleteModel(
            name='TadFile',
        ),
    ]
