# Generated by Django 4.1.3 on 2023-02-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snslaw', '0005_newtadfile_delete_tadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtadfile',
            name='file_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snslaw.clientfiles'),
        ),
    ]
