# Generated by Django 4.1.3 on 2023-03-04 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snslaw', '0007_newtadfile_superior_alter_newtadfile_file_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclient',
            name='birth_date',
            field=models.DateField(default=datetime.date(1993, 8, 8), verbose_name='תאריך לידה'),
        ),
    ]
